services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=/workspaces/ros2_websocket
    volumes:
      - ../:/workspaces/ros2_websocket
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=$DISPLAY
    network_mode: host
    cap_add: 
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: sleep infinity
    user: ros
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]